name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - main # Set this to the branch you want to deploy from

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js (if needed)
              uses: actions/setup-node@v2
              with:
                  node-version: '18' # Specify your Node.js version here

            - name: Install Dependencies
              run: yarn install # Adjust this line based on your project's dependency manager

            - name: Build
              run: yarn build

            - name: Deploy to Cloudflare Pages using Wrangler
              uses: cloudflare/wrangler-action@1.3.0
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  environment: 'production' # Adjust as needed
