name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - main # Set this to the branch you want to deploy from

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18' # Specify your Node.js version here

            - name: Install Dependencies
              run: yarn install # Adjust this line based on your project's dependency manager

            - name: Build
              run: yarn build

            - name: Deploy to Cloudflare Pages using Wrangler
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
